### ISSUE TITLE
ODRC: implement informatiecategorie resource

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#14]
Every published document belongs to a particular information category. The possible information categories are defined in a "waardelijst" published as part of the DiWoo standard (`informatiecategorielijst` in `diwoo-metadata-lijsten.xsd`). Additionally, organisaties want to define their own information categories (see #9).

The publication tool needs access to these categories so the correct metadata can be attached to documents.

Roughly the schema of `InformatieCategorie` would look like:

```yaml
InformatieCategorie:
  type: object
  properties:
    identifier:
      type: string
      format: uri
    order:
      type: number  # integer
    name:
      type: string
    namePlural:
      type: string
    definition:
      type: string
    origin:
      type: string
      enum:
        - waardelijst
        - zelf_toegevoegd  # can be edited, others cannot
```

Waardelijst: https://standaarden.overheid.nl/tooi/waardelijsten/expression?lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Fscw_woo_informatiecategorieen%2F3

- [x] Define model for `InformatieCategorie` and integrate it in the admin interface
    - Search on `identifier` and `name`
    - Order by `order`
    - List filter on `origin`
    - `identifier` is never editable
- [x] Add READ endpoint(s) `/api/v1/informatiecategorieen`
    - List endpoint: filter/search on `name`, `origin`
    - Paginate list endpoint
    - Detail endpoint: defaults from model viewset is okay
    - Create/update is out of scope, tackle that in #9
- [x] Add management command to populate the table from the waardelijst
    - Result must dump a django fixture (using natural keys!)
    - Fixture must be loaded automatically on deploys (post-migrate hook) so that the docker image contains the necessary data
