### ISSUE TITLE
Add API endpoint for CRU operations /api/v1/organisatie-onderdelen

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#34]

**Comment by sergei-maertens** [comment]
Draft data model (API resource)

```yaml
OrganisatieOnderdeel:
  type: object
  properties:
    name:
      type: string
    organisatie:
      $ref: '#!/Organisatie.properties.identifier'
    publicatieStatus:  # all records can be activated/deactivated
      type: string
      enum:
        - actief
        - niet_actief
```
