### ISSUE TITLE
Expose owner/creator of Publicatie and allow filtering

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#69]
### Thema / Theme

API

### Omschrijving / Description

Filtering the "own" publications in the UI (by the ODPC BFF) requires the filter parameter to exist on our end, and the information to be extracted.

This depends on the #16 and audit logging added via #35 to register the information about "ownership".

Extra field to expose on the `Publicatie` resource:

```yaml
eigenaar:
  type: object
  properties:
    weergaveNaam:  # obtained from the audit trail request headers, extracted from the audit trails/log entries
      type: string
    identifier:  # arbitrary, unique-ish string. Could be a `sub` claim from OIDC, but for our perspective this data has no "meaning"
      type: string
```

**Tasks**

- [x] Expose `eigenaar` field
- [x] Add filter parameter `eigenaar` to list API endpoint for `Publicatie`. The field must be an exact match on `eigenaar.identifier`.

### Toegevoegde waarde / Added value

Being able to finish GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#8
